# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: widgets.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'widgets.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rwidgets.proto\x12\x07widgets\"C\n\x13\x43reateWindowRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"8\n\x14\x43reateWindowResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2^\n\rWidgetService\x12M\n\x0c\x43reateWindow\x12\x1c.widgets.CreateWindowRequest\x1a\x1d.widgets.CreateWindowResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'widgets_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEWINDOWREQUEST']._serialized_start=26
  _globals['_CREATEWINDOWREQUEST']._serialized_end=93
  _globals['_CREATEWINDOWRESPONSE']._serialized_start=95
  _globals['_CREATEWINDOWRESPONSE']._serialized_end=151
  _globals['_WIDGETSERVICE']._serialized_start=153
  _globals['_WIDGETSERVICE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
